# Generated by Django 3.2.8 on 2021-10-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(default=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
